from __future__ import annotations

from typing import Any


def _scene(
    mode: str,
    anchors: list[str],
    action: str,
    place: str,
    motion: str = "reenactment_push",
) -> dict[str, Any]:
    return {"mode": mode, "anchors": anchors, "action": action, "place": place, "motion": motion}


# Approved EP02 narration-to-scene mappings. Exact narration binding is intentional:
# a script change must fail closed until its visual meaning is reviewed again.
EP02_SCENES_BY_DIGEST: dict[str, dict[str, Any]] = {
    "여기서 사건 자체를 완전한 조작이라 단정할 수는 없습니다.": _scene(
        "evidence_artifact",
        ["partly uncovered wrapped bundle", "undisturbed soil edge", "two cautious investigators"],
        "two investigators compare a partly uncovered cloth-wrapped bundle with an undisturbed patch of soil, withholding judgment",
        "quiet palace courtyard excavation",
        "artifact_close_push",
    ),
    "제시된 실록 문장은 발각된 내용을 분명히 전합니다.": _scene(
        "evidence_artifact",
        ["closed evidence chest", "wrapped ritual objects", "examining officials"],
        "officials inspect wrapped ritual objects placed beside one closed blank evidence chest, with every surface unmarked",
        "royal evidence chamber",
        "artifact_close_push",
    ),
    "다만 기록된 사건과 후대의 과장은 구별해야 합니다.": _scene(
        "analogy_explainer",
        ["small wrapped evidence bundle", "oversized theatre shadow", "rope boundary"],
        "a verified wrapped bundle rests inside a plain rope boundary while an oversized theatre-mask shadow falls outside it",
        "empty palace rehearsal courtyard",
        "analogy_pan",
    ),
    "신당과 흉물은 확인되지만 사약 난동은 확인되지 않지요.": _scene(
        "historical_reconstruction",
        ["small shrine alcove", "wrapped ritual bundle", "untouched medicine bowl"],
        "investigators examine a small shrine alcove and wrapped ritual bundle while an intact medicine bowl remains untouched far away",
        "Chwiseondang courtyard",
    ),
    "같은 인물을 다룬다고 모든 일화가 같은 무게는 아닙니다.": _scene(
        "analogy_explainer",
        ["brass balance", "sealed archive case", "three wooden stage masks"],
        "one sealed blank archive case outweighs three lightweight wooden stage masks on a large brass balance",
        "plain palace alcove",
        "analogy_pan",
    ),
    "사료마다 무엇을 실제로 적었는지 따로 물어야 하지요.": _scene(
        "evidence_artifact",
        ["red-cord record case", "blue-cord record case", "two archivists"],
        "two archivists carry differently corded closed record cases toward separate empty shelf bays, never opening either case",
        "royal archive aisle",
        "artifact_close_push",
    ),
    "이 차이를 놓치면 사실과 연출이 한데 섞입니다.": _scene(
        "analogy_explainer",
        ["archive chest", "theatre curtain", "clear floor boundary"],
        "a theatre curtain spills toward a sealed archive chest but stops at a clearly visible plain floor boundary",
        "palace rehearsal chamber",
        "analogy_pan",
    ),
    "사건의 문을 연 것은 신당과 흉물의 발각이었습니다.": _scene(
        "character_action",
        ["opening courtyard gate", "shrine alcove", "wrapped bundle"],
        "palace investigators push open a courtyard gate and immediately discover a shrine alcove with one wrapped bundle",
        "Chwiseondang west courtyard",
    ),
    "그러나 그 문 뒤에는 궁중만이 아니라 정치가 있었지요.": _scene(
        "historical_reconstruction",
        ["open inner-palace gate", "council officials", "sealed command case"],
        "beyond an open inner-palace gate, council officials gather around a sealed command case as the private incident enters politics",
        "passage between inner palace and council hall",
    ),
    "다음 장에서는 고변과 세력 결집을 함께 보겠습니다.": _scene(
        "historical_reconstruction",
        ["palace informant", "sealed testimony pouch", "gathering officials"],
        "a palace informant hands a sealed blank testimony pouch to an official while several allied officials gather behind him",
        "outer court gate",
    ),
    "숙빈 최씨의 고변은 숙종에게 정치적 명분을 주었습니다. 서인 세력의 결집도 그 결단을 뒷받침했지요.": _scene(
        "historical_reconstruction",
        ["royal testimony pouch", "King Sukjong", "aligned western officials"],
        "King Sukjong receives a sealed testimony pouch while a disciplined row of allied officials closes ranks behind the messenger",
        "royal council hall",
    ),
    "연구는 두 요소가 국왕의 선택을 재촉했다고 봅니다.": _scene(
        "diagram_metaphor",
        ["sealed accusation pouch", "ring of official hats", "royal command case"],
        "a sealed accusation pouch and a ring of official hats pull two plain cords that slide a royal command case toward the throne",
        "minimal council-hall floor",
        "diagram_reveal",
    ),
    "따라서 이 사건을 질투 하나로 줄이면 구조가 사라집니다.": _scene(
        "analogy_explainer",
        ["small cracked hand mirror", "palace gate network", "grouped officials"],
        "a small cracked hand mirror lies in the foreground while multiple palace gates and organized official groups dominate the larger scene",
        "wide royal compound",
        "analogy_pan",
    ),
    "궁중의 고변은 곧 조정의 정치 언어로 번졌습니다. 서인의 지지는 결단을 실행할 기반이 되었습니다.": _scene(
        "historical_reconstruction",
        ["inner-palace messenger", "sealed evidence case", "waiting council faction"],
        "a messenger carries a sealed evidence case from the inner-palace gate into a council hall where an organized faction turns toward it",
        "royal council entrance",
    ),
    "숙종에게는 처분을 정당화할 명분이 더해졌지요.": _scene(
        "diagram_metaphor",
        ["sealed testimony case", "allied official cords", "royal command box"],
        "a sealed testimony case and several joined official cords settle beside a royal command box in a compact left-side vignette",
        "sparse royal forecourt",
        "diagram_reveal",
    ),
    "여기서 중요한 말은 우발이 아니라 정치적 결단입니다.": _scene(
        "historical_reconstruction",
        ["King Sukjong", "deliberately placed command case", "still council floor"],
        "King Sukjong deliberately places a closed royal command case across the center line of a motionless council floor",
        "royal council hall",
    ),
    "권력의 저울추가 옮겨간 셈이지요.": _scene(
        "diagram_metaphor",
        ["oversized royal balance", "accusation pouch", "cluster of official hats"],
        "an oversized royal balance tips as a sealed accusation pouch and a cluster of official hats shift onto the same side",
        "minimal palace forecourt",
        "diagram_reveal",
    ),
    "고변은 불씨였고 세력 결집은 바람처럼 작용했습니다.": _scene(
        "analogy_explainer",
        ["small covered brazier ember", "fluttering official sleeves", "gathering ministers"],
        "a tiny ember glows inside a safe covered brazier while the sleeves of converging ministers create a visible current of air around it",
        "stone council courtyard",
        "analogy_pan",
    ),
    "물론 비유는 구조를 돕는 설명일 뿐 사료 문구는 아닙니다.": _scene(
        "evidence_artifact",
        ["wooden balance model", "sealed archive case", "archivist setting model aside"],
        "an archivist sets a small wooden balance model aside and centers a sealed blank archive case as the actual evidence",
        "plain archive work alcove without papers",
        "artifact_close_push",
    ),
    "사건의 책임과 정치적 활용은 함께 살펴야 합니다.": _scene(
        "historical_reconstruction",
        ["wrapped ritual evidence", "royal command case", "two official groups"],
        "one group carries wrapped ritual evidence toward the throne while another receives a sealed royal command case for political action",
        "royal council approach",
    ),
    "이제 반대 목소리가 실제로 있었는지 확인해 보겠습니다.": _scene(
        "historical_reconstruction",
        ["approaching senior ministers", "open petitioning hands", "distant throne"],
        "several senior ministers enter in a restrained line with open petitioning hands as the throne waits at the far end",
        "royal council hall entrance",
    ),
    "모든 신하가 한뜻이었다는 그림부터 걷어내야 합니다.": _scene(
        "historical_reconstruction",
        ["divided minister rows", "central empty aisle", "uneasy court faces"],
        "ministers occupy two visibly divided rows across a central empty aisle, some petitioning and others remaining uneasy and silent",
        "royal council hall",
    ),
    "승정원일기에는 대신들의 강한 반대가 남아 있습니다.": _scene(
        "historical_reconstruction",
        ["kneeling senior ministers", "closed petition cases", "firm throne"],
        "senior ministers kneel with closed blank petition cases and raised open hands before a firm distant throne",
        "royal council hall",
    ),
    "영의정 최석항 등은 극형을 막으려 힘써 간했습니다. 그들이 내세운 이유는 세자의 생모라는 지위였습니다.": _scene(
        "historical_reconstruction",
        ["elder chief minister", "crown-prince ceremonial chair", "King Sukjong"],
        "an elder chief minister kneels between King Sukjong and the crown prince's empty ceremonial chair, pleading with both hands raised",
        "royal council hall",
    ),
    "세자의 생모에게 사형을 더해서는 안 된다고 했지요.": _scene(
        "historical_reconstruction",
        ["protective elder minister", "women's quarters doorway", "crown-prince robe stand"],
        "an elder minister holds both open hands before the closed women's-quarters doorway while a small crown-prince robe stand remains nearby",
        "inner-palace passage",
    ),
    "하지만 숙종은 그 간언을 받아들이지 않았습니다.": _scene(
        "historical_reconstruction",
        ["King Sukjong turning away", "kneeling ministers", "sealed command case"],
        "King Sukjong turns away from kneeling ministers while keeping a sealed royal command case firmly beside the throne",
        "royal council hall",
    ),
    "이 대목은 조정의 의견이 하나가 아니었음을 보여 줍니다.": _scene(
        "historical_reconstruction",
        ["opposing minister groups", "clear central aisle", "watching king"],
        "two minister groups face different directions across a clear central aisle while the king watches from beyond them",
        "royal council hall",
    ),
    "반대가 존재했다는 사실은 결단의 무게를 더합니다.": _scene(
        "diagram_metaphor",
        ["heavy petition cases", "single royal command case", "bowed ministers"],
        "several heavy closed petition cases press against one royal command case as bowed ministers hold their positions",
        "bare council-hall floor",
        "diagram_reveal",
    ),
    "왕은 신하들의 제동을 알고도 뜻을 굽히지 않았지요.": _scene(
        "historical_reconstruction",
        ["ceremonial restraint rope", "petitioning ministers", "advancing command case"],
        "petitioning ministers hold a ceremonial restraint rope while King Sukjong advances the sealed command case beyond it",
        "royal council hall",
    ),
    "최석항 등의 간언은 체모와 왕실 질서를 붙들려 했습니다.": _scene(
        "historical_reconstruction",
        ["senior ministers", "ceremonial screen", "crown-prince chair"],
        "senior ministers steady a formal screen beside the crown prince's ceremonial chair while presenting closed petition cases",
        "royal ceremonial chamber",
    ),
    "숙종의 거부는 처분 의지가 확고했음을 드러냅니다.": _scene(
        "historical_reconstruction",
        ["King Sukjong", "sealed command case", "bowed ministers"],
        "King Sukjong places both hands firmly on a sealed command case while the ministers remain bowed at a respectful distance",
        "uncluttered royal council hall",
    ),
    "이 장면에 만장일치의 환호는 들어설 자리가 없습니다.": _scene(
        "historical_reconstruction",
        ["silent divided court", "lowered hands", "uneasy ministers"],
        "the divided court remains silent with lowered hands, bowed heads, and uneasy faces; nobody celebrates or raises a fist",
        "royal council hall",
    ),
    "정치적 결단과 왕실의 체모가 정면으로 맞선 셈이지요.": _scene(
        "diagram_metaphor",
        ["royal command case", "crown-prince ceremonial chair", "clear opposing floor lines"],
        "a sealed royal command case and the crown prince's ceremonial chair face each other across two opposing floor lines",
        "minimal ceremonial chamber",
        "diagram_reveal",
    ),
    "기록은 논쟁의 승자를 숙종으로 남겼습니다. 그러나 반대자의 목소리까지 지우지는 않았습니다.": _scene(
        "evidence_artifact",
        ["red-cord royal case", "blue-cord minister case", "shared archive shelf"],
        "a red-cord royal record case and a blue-cord minister record case are preserved side by side on one plain archive shelf",
        "quiet royal archive",
        "artifact_close_push",
    ),
    "바로 그 기록 덕분에 처분의 갈등을 읽을 수 있지요.": _scene(
        "evidence_artifact",
        ["two closed record cases", "crossing light beams", "careful archivist"],
        "an archivist holds two differently corded closed record cases where crossing beams of window light reveal their equal preservation",
        "royal archive alcove",
        "artifact_close_push",
    ),
    "다음은 왕이 선택한 자진이라는 형식입니다.": _scene(
        "historical_reconstruction",
        ["closed royal command tube", "women's quarters threshold", "waiting court lady"],
        "a court lady waits solemnly as a messenger places one closed royal command tube outside the women's-quarters threshold",
        "inner-palace women's quarters",
    ),
    "숙종실록의 핵심 동사는 자진을 명했다는 것입니다.": _scene(
        "historical_reconstruction",
        ["King Sukjong", "sealed command baton", "bowing messenger"],
        "King Sukjong dispatches a sealed command baton toward the women's quarters as a messenger bows to receive it",
        "royal audience chamber",
    ),
    "이는 스스로 목숨을 끊도록 명한 처분 형식입니다. 왕은 세자 생모의 체모를 대략 갖추게 했습니다.": _scene(
        "atmosphere",
        ["solemn royal woman", "folded ceremonial robe", "closed command case"],
        "a dignified royal woman sits upright behind a plain screen while attendants place a folded ceremonial robe and closed command case nearby",
        "quiet private palace chamber",
        "atmosphere_drift",
    ),
    "강제로 약을 들이붓는 장면은 이 기록에 없습니다.": _scene(
        "evidence_artifact",
        ["intact medicine bowl", "empty-handed attendants", "respectful distance"],
        "an intact medicine bowl remains on a plain tray at a respectful distance while every attendant stands back with empty hands",
        "quiet private palace chamber",
        "artifact_close_push",
    ),
    "망나니가 나서는 식의 집행도 근거에서 확인되지 않지요.": _scene(
        "atmosphere",
        ["empty palace passage", "unarmed official messenger", "closed command case"],
        "an unarmed official messenger walks alone through an empty palace passage carrying only a closed command case",
        "inner-palace corridor",
        "atmosphere_drift",
    ),
    "승정원일기 역시 사사의 명이 집행됐다고 전합니다. 그 기록은 집행 과정에 체모가 갖추어졌다고 적습니다.": _scene(
        "historical_reconstruction",
        ["senior court lady", "official messenger", "formal chamber screen"],
        "a senior court lady receives a closed command case from an official messenger at a formal chamber screen while attendants bow",
        "women's-quarters threshold",
    ),
    "이어 희빈이 법을 받자 궁중이 숙연해졌다고 전하지요.": _scene(
        "atmosphere",
        ["silent palace courtyard", "bowed attendants", "extinguished lanterns"],
        "attendants stand silently with bowed heads among extinguished lanterns in a still palace courtyard",
        "inner-palace courtyard",
        "atmosphere_drift",
    ),
    "여기에는 고함과 난동보다 행정적이고 절제된 문장이 남습니다.": _scene(
        "historical_reconstruction",
        ["orderly officials", "single closed command case", "quiet corridor"],
        "orderly officials carry one closed command case through a quiet corridor in measured formation without any commotion",
        "royal administrative corridor",
    ),
    "그럼에도 두 사료는 자진과 체모라는 방향에서 만납니다.": _scene(
        "evidence_artifact",
        ["two sealed record cases", "folded ceremonial robe", "converging cords"],
        "two sealed record cases with red and blue cords converge beside one neatly folded ceremonial robe on a plain floor",
        "sparse archive chamber",
        "artifact_close_push",
    ),
    "따라서 사약 소동을 정사의 사실처럼 말할 수 없습니다.": _scene(
        "analogy_explainer",
        ["tied theatre curtain", "overturned stage bowl", "closed archive gate"],
        "an archivist closes a plain archive gate against an overturned stage bowl and a tied theatre curtain left outside",
        "archive courtyard entrance",
        "analogy_pan",
    ),
    "자진은 자비로운 석방이 아니라 죽음을 명한 처분입니다.": _scene(
        "atmosphere",
        ["closed chamber door", "black command case", "plain mourning cloth"],
        "a closed chamber door stands behind a dark sealed command case and one plain mourning cloth, with no sign of release or celebration",
        "inner-palace passage",
        "atmosphere_drift",
    ),
    "동시에 집행 형식에는 세자 생모의 지위가 반영됐지요.": _scene(
        "historical_reconstruction",
        ["formal court ladies", "ceremonial robe", "distant male officials"],
        "court ladies arrange a formal ceremonial robe and screen near the chamber while male officials remain at a respectful distance",
        "women's-quarters courtyard",
    ),
    "이 두 측면을 함께 보아야 기록을 과장하지 않습니다.": _scene(
        "diagram_metaphor",
        ["cold command case", "respectful ceremonial screen", "shared chamber floor"],
        "a cold sealed command case and a respectful ceremonial screen occupy equal sides of one uncluttered chamber floor",
        "minimal private chamber",
        "diagram_reveal",
    ),
    "차가운 명령과 최소한의 체모가 한 문장에 공존합니다.": _scene(
        "evidence_artifact",
        ["dark sealed command box", "folded royal garment", "bare floor"],
        "a dark sealed command box rests beside one neatly folded royal garment on a bare unmarked floor",
        "quiet palace chamber",
        "artifact_close_push",
    ),
    "그 공존이야말로 실제 최후의 성격을 선명하게 합니다.": _scene(
        "atmosphere",
        ["quiet closed chamber", "sealed command case", "bowed attendants"],
        "bowed attendants wait outside a quiet closed chamber where a sealed command case and folded robe remain visible",
        "inner-palace corridor",
        "atmosphere_drift",
    ),
    "이제 처분 뒤에 남은 제도적 흔적을 보지요.": _scene(
        "diagram_metaphor",
        ["palace gate beam", "new locking pin", "empty ascending path"],
        "a new wooden locking pin is fitted into a palace gate beam above an empty ascending path",
        "royal women's palace gate",
        "diagram_reveal",
    ),
    "숙종은 후궁의 중전 승격을 금하는 법을 세웠습니다.": _scene(
        "diagram_metaphor",
        ["concubine-quarters stair", "permanent wooden barrier", "queen's hall"],
        "craftsmen fit a permanent wooden barrier across the stair rising from the concubine quarters toward the queen's hall",
        "royal women's palace",
        "diagram_reveal",
    ),
    "실록은 이를 만세의 법으로 정하라고 전합니다.": _scene(
        "diagram_metaphor",
        ["receding palace gates", "single durable lock beam", "future attendants"],
        "a durable lock beam spans the nearest of several receding palace gates as future attendants pass beneath the fixed boundary",
        "long royal palace passage",
        "diagram_reveal",
    ),
    "비록 큰 공이 있어도 승격할 수 없다는 내용이었지요.": _scene(
        "diagram_metaphor",
        ["decorated award chest", "blocked palace stair", "queen's ceremonial chair"],
        "a decorated but unmarked award chest stops before a wooden barrier across the stair leading to the queen's ceremonial chair",
        "royal women's palace stair",
        "diagram_reveal",
    ),
    "장희빈의 죽음 뒤에는 이 제도적 금지가 남았습니다.": _scene(
        "atmosphere",
        ["empty sealed stair", "weathered crossbeam", "fallen autumn leaves"],
        "fallen autumn leaves gather around a weathered crossbeam that permanently seals an empty palace stair",
        "women's palace courtyard",
        "atmosphere_drift",
    ),
    "후궁에서 중전으로 오르는 길을 영구히 막았지요. 이 법은 같은 승격이 되풀이되는 가능성을 차단했습니다.": _scene(
        "diagram_metaphor",
        ["ascending palace walkway", "heavy closed gate", "queen's hall beyond"],
        "a heavy closed gate permanently blocks the ascending walkway from the concubine quarters to the queen's hall beyond",
        "royal women's palace",
        "diagram_reveal",
    ),
    "숙종의 선택은 한 사람의 생애에서 멈추지 않았습니다.": _scene(
        "diagram_metaphor",
        ["closed private chamber", "long royal command cord", "massive gate lock"],
        "a long royal command cord runs from a closed private chamber to a massive institutional gate lock",
        "wide palace compound",
        "diagram_reveal",
    ),
    "왕실의 지위 질서 자체를 다시 정하는 데 이르렀지요.": _scene(
        "historical_reconstruction",
        ["two ceremonial chairs", "separate floor levels", "fixed central barrier"],
        "palace attendants reposition two ceremonial chairs on clearly separate floor levels divided by a fixed central barrier",
        "royal ceremonial hall",
    ),
    "앞선 환국 정치와 함께 보면 방향이 더욱 또렷합니다.": _scene(
        "historical_reconstruction",
        ["opposing council groups", "locked inner gate", "central king"],
        "opposing council groups and a locked inner-palace gate align beneath King Sukjong's central position",
        "wide royal council courtyard",
    ),
    "외척의 부상은 견제되고 왕의 통제력은 강화되었습니다.": _scene(
        "historical_reconstruction",
        ["halted family carriages", "closing royal gate", "central palace guard"],
        "outer-family carriages halt outside as palace guards close the royal gate and secure the central passage",
        "main royal palace gate",
    ),
    "연구는 장희빈 처형도 그 정치적 결단으로 설명합니다.": _scene(
        "diagram_metaphor",
        ["King Sukjong", "plain faction stones", "single royal token"],
        "King Sukjong moves one large royal token between two groups of plain faction stones on the bare council floor",
        "minimal royal council hall",
        "diagram_reveal",
    ),
    "제도는 사건이 지나간 뒤에도 권력의 뜻을 보존합니다.": _scene(
        "atmosphere",
        ["old palace gate lock", "changing seasonal leaves", "passing attendants"],
        "an old palace gate lock remains fixed while leaves from changing seasons gather and new attendants pass by",
        "royal palace passage",
        "atmosphere_drift",
    ),
    "만세의 법이라는 표현은 그 지속 의지를 드러냅니다.": _scene(
        "diagram_metaphor",
        ["deep-set locking pin", "stone gate foundation", "long palace path"],
        "a deep-set wooden locking pin anchors into a stone gate foundation beside a long palace path extending into the distance",
        "royal palace gate",
        "diagram_reveal",
    ),
    "이제 일곱 번째 장에서 기록과 기억을 정리하겠습니다.": _scene(
        "place_establishing",
        ["sealed archive chest", "intact medicine bowl", "locked palace gate"],
        "one continuous palace path passes a sealed archive chest, an intact medicine bowl on a pedestal, and a locked gate as successive landmarks",
        "broad palace courtyard path",
        "place_sweep",
    ),
    "한 인간의 죽음을 자극적인 구경거리로만 남겨선 안 됩니다.": _scene(
        "atmosphere",
        ["closed theatre curtain", "empty audience benches", "plain white mourning cloth"],
        "a closed theatre curtain faces empty audience benches while one plain white mourning cloth rests quietly outside the stage",
        "empty palace theatre courtyard",
        "atmosphere_drift",
    ),
    "숙빈 최씨의 고변과 서인의 결집도 명분을 제공했습니다.": _scene(
        "historical_reconstruction",
        ["sealed accusation pouch", "palace messenger", "aligned allied officials"],
        "a palace messenger hands over a sealed accusation pouch as allied officials align behind the receiving minister",
        "outer royal court",
    ),
    "그 극적인 장면은 야담과 소설의 영역에 속합니다.": _scene(
        "analogy_explainer",
        ["wooden theatre mask", "overturned stage bowl", "tied curtain"],
        "a wooden theatre mask and overturned stage bowl remain behind a tied theatre curtain, isolated from the palace archive",
        "palace rehearsal chamber",
        "analogy_pan",
    ),
    "사후에는 후궁의 중전 승격을 막는 법까지 세워졌습니다.": _scene(
        "diagram_metaphor",
        ["barred palace steps", "queen's ceremonial chair", "permanent gate beam"],
        "a permanent gate beam bars the palace steps leading from the lower quarters to the queen's ceremonial chair",
        "royal women's palace",
        "diagram_reveal",
    ),
    "이렇게 놓고 보면 악녀 한 사람의 이야기가 아니지요.": _scene(
        "place_establishing",
        ["inner palace quarters", "royal council hall", "locked institutional gate"],
        "a wide coherent palace view links the inner quarters, council hall, and locked institutional gate with several groups rather than one central woman",
        "wide royal palace compound",
        "place_sweep",
    ),
    "제가 보기엔 기록의 절제가 오히려 권력의 냉기를 전합니다.": _scene(
        "atmosphere",
        ["frosted archive window", "sealed command case", "long throne shadow"],
        "cold window light falls across a sealed command case whose long shadow reaches toward an empty throne",
        "quiet royal archive chamber",
        "atmosphere_drift",
    ),
    "누군가의 최후를 소비하기 전 근거부터 묻는 까닭입니다. 사료는 장희빈을 미화하라고 요구하지 않습니다.": _scene(
        "historical_reconstruction",
        ["careful archivist", "sealed evidence chest", "stopped theatre crowd"],
        "a careful archivist stops a small crowd from entering a theatre and redirects them toward a sealed blank evidence chest",
        "archive gate beside rehearsal courtyard",
    ),
    "또한 근거 없는 잔혹 장면을 사실로 믿으라 하지도 않지요.": _scene(
        "analogy_explainer",
        ["tied execution-prop curtain", "turning investigators", "sealed archive chest"],
        "investigators turn away from theatrical punishment props hidden behind a tied curtain and walk toward a sealed archive chest",
        "palace rehearsal courtyard",
        "analogy_pan",
    ),
    "우리가 할 일은 확인된 책임과 후대 연출을 가르는 것입니다.": _scene(
        "evidence_artifact",
        ["wrapped ritual evidence", "wooden stage mask", "two separate closed boxes"],
        "two investigators sort a wrapped ritual evidence bundle and a wooden stage mask into two clearly separate closed blank boxes",
        "plain evidence courtyard",
        "artifact_close_push",
    ),
    "그 경계에서 장희빈의 인간적 존엄도 지킬 수 있습니다.": _scene(
        "atmosphere",
        ["dignified royal woman silhouette", "plain folding screen", "evidence boundary rope"],
        "a dignified royal woman walks behind a plain folding screen while an archive chest and theatre mask remain outside a respectful boundary rope",
        "quiet inner-palace courtyard",
        "atmosphere_drift",
    ),
}
