# -*- coding: utf-8 -*-
"""V5 Strict Sequential ASS Subtitle Generator:
Maps dialogue events to the exact sequential timeline generated by build_master_audio_sequential_v5.py.
Enforces: 92pt Pretendard Bold, <=2 lines per event, <=16 chars per line, exact speech sync, 0 overlaps."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

EP_DIR = Path(r"D:\module\bible\human_archive\runs\nollam_file\2026-09-02\himalaya-glof-water-crisis")
MANIFEST_PATH = EP_DIR / "generation" / "master_sequential_v5_manifest.json"
OUT_ASS = EP_DIR / "candidate" / "subtitles_v5_sequential.ass"
QA_REPORT = EP_DIR / "candidate" / "subtitles_v5_qa_report.json"


def seconds_to_ass(s: float) -> str:
    cs = int(round(s * 100))
    m, cs = divmod(cs, 6000)
    h, m = divmod(m, 60)
    s_int, cs = divmod(cs, 100)
    return f"{h:d}:{m:02d}:{s_int:02d}.{cs:02d}"


def split_sentence_into_clauses(text: str, max_chars: int = 32) -> list[str]:
    text = text.strip()
    if len(text) <= max_chars:
        return [text]

    # 1. Punctuation comma near middle
    comma_matches = [m.end() for m in re.finditer(r"(?<!\d),(?!\d)\s*", text)]
    mid = len(text) / 2.0
    best_split = -1
    min_diff = 9999

    for pos in comma_matches:
        diff = abs(pos - mid)
        if diff < min_diff and 6 <= pos <= len(text) - 6:
            min_diff = diff
            best_split = pos

    # 2. Connective verb endings
    if best_split <= 0:
        conn_matches = [m.end() for m in re.finditer(r"(?:면|고|며|지만|는데|어서|하여|되어|수록|면서|하고|되고|이며|이나)\s+", text)]
        for pos in conn_matches:
            diff = abs(pos - mid)
            if diff < min_diff and 6 <= pos <= len(text) - 6:
                min_diff = diff
                best_split = pos

    # 3. Whitespace nearest to middle
    if best_split <= 0:
        words = text.split()
        if len(words) <= 1:
            return [text]

        best_idx = 1
        min_diff = 9999
        for i in range(1, len(words)):
            w1 = " ".join(words[:i])
            w2 = " ".join(words[i:])
            diff = abs(len(w1) - len(w2))
            if diff < min_diff:
                min_diff = diff
                best_idx = i
        best_split = len(" ".join(words[:best_idx]))

    c1 = text[:best_split].strip()
    c2 = text[best_split:].strip()

    res = []
    for c in [c1, c2]:
        if len(c) > max_chars:
            res.extend(split_sentence_into_clauses(c, max_chars=max_chars))
        else:
            res.append(c)
    return res


def split_clause_two_lines(text: str, max_line_chars: int = 16) -> str:
    text = text.strip()
    if len(text) <= max_line_chars:
        return text

    # Check comma split
    comma_matches = [m.end() for m in re.finditer(r"(?<!\d),(?!\d)\s*", text)]
    mid = len(text) / 2.0
    best_split = -1
    min_diff = 9999

    for pos in comma_matches:
        diff = abs(pos - mid)
        if diff < min_diff and 4 <= pos <= len(text) - 4:
            min_diff = diff
            best_split = pos

    if best_split > 0:
        l1 = text[:best_split].strip()
        l2 = text[best_split:].strip()
        return l1 + r"\N" + l2

    # Split by whitespace balanced near middle
    words = text.split()
    if len(words) <= 1:
        return text

    best_idx = 1
    min_diff = 9999
    for i in range(1, len(words)):
        l1 = " ".join(words[:i])
        l2 = " ".join(words[i:])
        diff = abs(len(l1) - len(l2))
        if diff < min_diff:
            min_diff = diff
            best_idx = i

    l1 = " ".join(words[:best_idx]).strip()
    l2 = " ".join(words[best_idx:]).strip()
    return l1 + r"\N" + l2


def main():
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    shots = manifest["shots"]
    print(f"🎬 Loaded {len(shots)} shots from V5 sequential manifest.")

    header = """[Script Info]
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: DocuNarrator_v5,Pretendard,92,&H00FFFFFF,&H000000FF,&H000C0C12,&H90000000,-1,0,0,0,100,100,0,0,1,6.0,3.2,2,140,140,85,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    dialogue_events = []
    all_intervals = []
    violations = []

    for s in shots:
        sid = s["shot_id"]
        display_text = s["display_text"]
        speech_start = s["speech_start"]
        speech_dur = s["speech_duration"]
        scene_end = s["scene_end"]

        max_shot_sub_end = scene_end - 0.10
        available_dur = max(1.0, max_shot_sub_end - speech_start)
        effective_dur = min(speech_dur, available_dur)

        raw_sents = [st.strip() for st in re.split(r"(?<=[.?!])\s+", display_text) if st.strip()]
        if not raw_sents:
            raw_sents = [display_text.strip()]

        total_chars = sum(len(st) for st in raw_sents)
        cur_t = speech_start

        for sent in raw_sents:
            ratio = len(sent) / max(1, total_chars)
            sent_dur = max(1.2, round(effective_dur * ratio, 3))

            clauses = split_sentence_into_clauses(sent, max_chars=32)
            total_clause_chars = sum(len(c) for c in clauses)

            clause_t = cur_t
            for clause in clauses:
                c_ratio = len(clause) / max(1, total_clause_chars)
                c_dur = max(0.9, round(sent_dur * c_ratio, 3))

                sub_start = round(clause_t, 2)
                sub_end = min(max_shot_sub_end, round(clause_t + c_dur - 0.04, 2))
                if sub_end <= sub_start:
                    sub_end = min(max_shot_sub_end, sub_start + 0.5)

                formatted_text = split_clause_two_lines(clause, max_line_chars=16)

                lines = formatted_text.split(r"\N")
                if len(lines) > 2:
                    violations.append({"shot_id": sid, "clause": clause, "error": f"Lines {len(lines)} > 2"})
                for line in lines:
                    if len(line) > 18:
                        violations.append({"shot_id": sid, "clause": clause, "error": f"Line length {len(line)} > 18"})

                start_ass = seconds_to_ass(sub_start)
                end_ass = seconds_to_ass(sub_end)
                dialogue_events.append(f"Dialogue: 0,{start_ass},{end_ass},DocuNarrator_v5,,0,0,0,,{formatted_text}")
                all_intervals.append((sub_start, sub_end, formatted_text))

                clause_t = sub_end + 0.04

            cur_t = clause_t + 0.04

    # Verification: Overlaps check across all subtitle events
    sub_overlaps = []
    for i in range(len(all_intervals) - 1):
        i1 = all_intervals[i]
        i2 = all_intervals[i + 1]
        if i1[1] > i2[0]:
            sub_overlaps.append({"event1": i1, "event2": i2, "overlap": round(i1[1] - i2[0], 3)})

    print(f"Generated {len(dialogue_events)} subtitle events.")
    print(f"Violations (lines>2 or len>18): {len(violations)}")
    print(f"Subtitle Overlaps: {len(sub_overlaps)}")

    ass_content = header + "\n".join(dialogue_events) + "\n"
    OUT_ASS.write_text(ass_content, encoding="utf-8")
    print(f"Saved V5 Subtitles: {OUT_ASS}")

    qa_report = {
        "status": "PASS" if len(violations) == 0 and len(sub_overlaps) == 0 else "FAIL",
        "total_events": len(dialogue_events),
        "total_violations": len(violations),
        "total_overlaps": len(sub_overlaps),
        "violations": violations[:10],
        "overlaps": sub_overlaps[:10],
    }
    QA_REPORT.write_text(json.dumps(qa_report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Saved QA Report: {QA_REPORT}")


if __name__ == "__main__":
    main()
